/*
 * generated by Xtext
 */
package org.xtext.banque.application.ui.contentassist

import org.xtext.banque.application.ui.contentassist.AbstractMyApplicationProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class MyApplicationProposalProvider extends AbstractMyApplicationProposalProvider {
}
