/*
* generated by Xtext
*/
package org.xtext.banque.application.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.banque.application.services.MyApplicationGrammarAccess;

public class MyApplicationParser extends AbstractContentAssistParser {
	
	@Inject
	private MyApplicationGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.banque.application.ui.contentassist.antlr.internal.InternalMyApplicationParser createParser() {
		org.xtext.banque.application.ui.contentassist.antlr.internal.InternalMyApplicationParser result = new org.xtext.banque.application.ui.contentassist.antlr.internal.InternalMyApplicationParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getUIApplicationAccess().getGroup(), "rule__UIApplication__Group__0");
					put(grammarAccess.getUIApplicationAccess().getGroup_3(), "rule__UIApplication__Group_3__0");
					put(grammarAccess.getUIApplicationAccess().getGroup_3_3(), "rule__UIApplication__Group_3_3__0");
					put(grammarAccess.getUIApplicationAccess().getGroup_4(), "rule__UIApplication__Group_4__0");
					put(grammarAccess.getUIApplicationAccess().getGroup_4_3(), "rule__UIApplication__Group_4_3__0");
					put(grammarAccess.getViewAccess().getGroup(), "rule__View__Group__0");
					put(grammarAccess.getViewAccess().getGroup_3(), "rule__View__Group_3__0");
					put(grammarAccess.getViewAccess().getGroup_6(), "rule__View__Group_6__0");
					put(grammarAccess.getViewAccess().getGroup_6_3(), "rule__View__Group_6_3__0");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getModelAccess().getGroup_4(), "rule__Model__Group_4__0");
					put(grammarAccess.getModelAccess().getGroup_4_3(), "rule__Model__Group_4_3__0");
					put(grammarAccess.getModelAccess().getGroup_5(), "rule__Model__Group_5__0");
					put(grammarAccess.getModelAccess().getGroup_5_3(), "rule__Model__Group_5_3__0");
					put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
					put(grammarAccess.getActionAccess().getGroup_4(), "rule__Action__Group_4__0");
					put(grammarAccess.getModelPropertyAccess().getGroup(), "rule__ModelProperty__Group__0");
					put(grammarAccess.getUIApplicationAccess().getPagesAssignment_3_2(), "rule__UIApplication__PagesAssignment_3_2");
					put(grammarAccess.getUIApplicationAccess().getPagesAssignment_3_3_1(), "rule__UIApplication__PagesAssignment_3_3_1");
					put(grammarAccess.getUIApplicationAccess().getModelsAssignment_4_2(), "rule__UIApplication__ModelsAssignment_4_2");
					put(grammarAccess.getUIApplicationAccess().getModelsAssignment_4_3_1(), "rule__UIApplication__ModelsAssignment_4_3_1");
					put(grammarAccess.getViewAccess().getNameAssignment_1(), "rule__View__NameAssignment_1");
					put(grammarAccess.getViewAccess().getDescriptionAssignment_3_1(), "rule__View__DescriptionAssignment_3_1");
					put(grammarAccess.getViewAccess().getModelAssignment_5(), "rule__View__ModelAssignment_5");
					put(grammarAccess.getViewAccess().getActionsAssignment_6_2(), "rule__View__ActionsAssignment_6_2");
					put(grammarAccess.getViewAccess().getActionsAssignment_6_3_1(), "rule__View__ActionsAssignment_6_3_1");
					put(grammarAccess.getModelAccess().getNameAssignment_2(), "rule__Model__NameAssignment_2");
					put(grammarAccess.getModelAccess().getPropertiesAssignment_4_2(), "rule__Model__PropertiesAssignment_4_2");
					put(grammarAccess.getModelAccess().getPropertiesAssignment_4_3_1(), "rule__Model__PropertiesAssignment_4_3_1");
					put(grammarAccess.getModelAccess().getOwnedElementsAssignment_5_2(), "rule__Model__OwnedElementsAssignment_5_2");
					put(grammarAccess.getModelAccess().getOwnedElementsAssignment_5_3_1(), "rule__Model__OwnedElementsAssignment_5_3_1");
					put(grammarAccess.getActionAccess().getNameAssignment_2(), "rule__Action__NameAssignment_2");
					put(grammarAccess.getActionAccess().getNextPageAssignment_4_1(), "rule__Action__NextPageAssignment_4_1");
					put(grammarAccess.getModelPropertyAccess().getNameAssignment_2(), "rule__ModelProperty__NameAssignment_2");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.banque.application.ui.contentassist.antlr.internal.InternalMyApplicationParser typedParser = (org.xtext.banque.application.ui.contentassist.antlr.internal.InternalMyApplicationParser) parser;
			typedParser.entryRuleUIApplication();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public MyApplicationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MyApplicationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
