/*
* generated by Xtext
*/
package org.xtext.banque.application;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MyApplicationUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.banque.application.ui.internal.MyApplicationActivator.getInstance().getInjector("org.xtext.banque.application.MyApplication");
	}
	
}
