/**
 * generated by Xtext
 */
package org.xtext.banque.application.serializer;

import org.xtext.banque.application.serializer.AbstractMyApplicationSyntacticSequencer;

@SuppressWarnings("all")
public class MyApplicationSyntacticSequencer extends AbstractMyApplicationSyntacticSequencer {
}
