/**
 * generated by Xtext
 */
package org.xtext.banque.application.serializer;

import org.xtext.banque.application.serializer.AbstractMyApplicationSemanticSequencer;

@SuppressWarnings("all")
public class MyApplicationSemanticSequencer extends AbstractMyApplicationSemanticSequencer {
}
