/*
* generated by Xtext
*/
package org.xtext.banque.application.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class MyApplicationGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class UIApplicationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "UIApplication");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cUIApplicationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cUIApplicationKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cPagesKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cPagesAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cPagesViewParserRuleCall_3_2_0 = (RuleCall)cPagesAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cPagesAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cPagesViewParserRuleCall_3_3_1_0 = (RuleCall)cPagesAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cModelsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cModelsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cModelsModelParserRuleCall_4_2_0 = (RuleCall)cModelsAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cModelsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cModelsModelParserRuleCall_4_3_1_0 = (RuleCall)cModelsAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//UIApplication:
		//	{UIApplication} "UIApplication" "{" ("pages" "{" pages+=View ("," pages+=View)* "}")? ("models" "{" models+=Model (","
		//	models+=Model)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//{UIApplication} "UIApplication" "{" ("pages" "{" pages+=View ("," pages+=View)* "}")? ("models" "{" models+=Model (","
		//models+=Model)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{UIApplication}
		public Action getUIApplicationAction_0() { return cUIApplicationAction_0; }

		//"UIApplication"
		public Keyword getUIApplicationKeyword_1() { return cUIApplicationKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("pages" "{" pages+=View ("," pages+=View)* "}")?
		public Group getGroup_3() { return cGroup_3; }

		//"pages"
		public Keyword getPagesKeyword_3_0() { return cPagesKeyword_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }

		//pages+=View
		public Assignment getPagesAssignment_3_2() { return cPagesAssignment_3_2; }

		//View
		public RuleCall getPagesViewParserRuleCall_3_2_0() { return cPagesViewParserRuleCall_3_2_0; }

		//("," pages+=View)*
		public Group getGroup_3_3() { return cGroup_3_3; }

		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }

		//pages+=View
		public Assignment getPagesAssignment_3_3_1() { return cPagesAssignment_3_3_1; }

		//View
		public RuleCall getPagesViewParserRuleCall_3_3_1_0() { return cPagesViewParserRuleCall_3_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }

		//("models" "{" models+=Model ("," models+=Model)* "}")?
		public Group getGroup_4() { return cGroup_4; }

		//"models"
		public Keyword getModelsKeyword_4_0() { return cModelsKeyword_4_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }

		//models+=Model
		public Assignment getModelsAssignment_4_2() { return cModelsAssignment_4_2; }

		//Model
		public RuleCall getModelsModelParserRuleCall_4_2_0() { return cModelsModelParserRuleCall_4_2_0; }

		//("," models+=Model)*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//models+=Model
		public Assignment getModelsAssignment_4_3_1() { return cModelsAssignment_4_3_1; }

		//Model
		public RuleCall getModelsModelParserRuleCall_4_3_1_0() { return cModelsModelParserRuleCall_4_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class ViewElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "View");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cViewKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDescriptionKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDescriptionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_3_1_0 = (RuleCall)cDescriptionAssignment_3_1.eContents().get(0);
		private final Keyword cModelKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cModelAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cModelModelCrossReference_5_0 = (CrossReference)cModelAssignment_5.eContents().get(0);
		private final RuleCall cModelModelEStringParserRuleCall_5_0_1 = (RuleCall)cModelModelCrossReference_5_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cActionsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cActionsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cActionsActionParserRuleCall_6_2_0 = (RuleCall)cActionsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cActionsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cActionsActionParserRuleCall_6_3_1_0 = (RuleCall)cActionsAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//View:
		//	"View" name=EString "{" ("description" description=EString)? "model" model=[Model|EString] ("actions" "{"
		//	actions+=Action ("," actions+=Action)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//"View" name=EString "{" ("description" description=EString)? "model" model=[Model|EString] ("actions" "{"
		//actions+=Action ("," actions+=Action)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//"View"
		public Keyword getViewKeyword_0() { return cViewKeyword_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("description" description=EString)?
		public Group getGroup_3() { return cGroup_3; }

		//"description"
		public Keyword getDescriptionKeyword_3_0() { return cDescriptionKeyword_3_0; }

		//description=EString
		public Assignment getDescriptionAssignment_3_1() { return cDescriptionAssignment_3_1; }

		//EString
		public RuleCall getDescriptionEStringParserRuleCall_3_1_0() { return cDescriptionEStringParserRuleCall_3_1_0; }

		//"model"
		public Keyword getModelKeyword_4() { return cModelKeyword_4; }

		//model=[Model|EString]
		public Assignment getModelAssignment_5() { return cModelAssignment_5; }

		//[Model|EString]
		public CrossReference getModelModelCrossReference_5_0() { return cModelModelCrossReference_5_0; }

		//EString
		public RuleCall getModelModelEStringParserRuleCall_5_0_1() { return cModelModelEStringParserRuleCall_5_0_1; }

		//("actions" "{" actions+=Action ("," actions+=Action)* "}")?
		public Group getGroup_6() { return cGroup_6; }

		//"actions"
		public Keyword getActionsKeyword_6_0() { return cActionsKeyword_6_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6_1() { return cLeftCurlyBracketKeyword_6_1; }

		//actions+=Action
		public Assignment getActionsAssignment_6_2() { return cActionsAssignment_6_2; }

		//Action
		public RuleCall getActionsActionParserRuleCall_6_2_0() { return cActionsActionParserRuleCall_6_2_0; }

		//("," actions+=Action)*
		public Group getGroup_6_3() { return cGroup_6_3; }

		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }

		//actions+=Action
		public Assignment getActionsAssignment_6_3_1() { return cActionsAssignment_6_3_1; }

		//Action
		public RuleCall getActionsActionParserRuleCall_6_3_1_0() { return cActionsActionParserRuleCall_6_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6_4() { return cRightCurlyBracketKeyword_6_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cModelKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cPropertiesKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cPropertiesAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cPropertiesModelPropertyParserRuleCall_4_2_0 = (RuleCall)cPropertiesAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cPropertiesAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cPropertiesModelPropertyParserRuleCall_4_3_1_0 = (RuleCall)cPropertiesAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cOwnedElementsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cOwnedElementsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cOwnedElementsModelParserRuleCall_5_2_0 = (RuleCall)cOwnedElementsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cOwnedElementsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cOwnedElementsModelParserRuleCall_5_3_1_0 = (RuleCall)cOwnedElementsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Model:
		//	{Model} "Model" name=EString "{" ("properties" "{" properties+=ModelProperty ("," properties+=ModelProperty)* "}")?
		//	("ownedElements" "{" ownedElements+=Model ("," ownedElements+=Model)* "}")? "}";
		public ParserRule getRule() { return rule; }

		//{Model} "Model" name=EString "{" ("properties" "{" properties+=ModelProperty ("," properties+=ModelProperty)* "}")?
		//("ownedElements" "{" ownedElements+=Model ("," ownedElements+=Model)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{Model}
		public Action getModelAction_0() { return cModelAction_0; }

		//"Model"
		public Keyword getModelKeyword_1() { return cModelKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("properties" "{" properties+=ModelProperty ("," properties+=ModelProperty)* "}")?
		public Group getGroup_4() { return cGroup_4; }

		//"properties"
		public Keyword getPropertiesKeyword_4_0() { return cPropertiesKeyword_4_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }

		//properties+=ModelProperty
		public Assignment getPropertiesAssignment_4_2() { return cPropertiesAssignment_4_2; }

		//ModelProperty
		public RuleCall getPropertiesModelPropertyParserRuleCall_4_2_0() { return cPropertiesModelPropertyParserRuleCall_4_2_0; }

		//("," properties+=ModelProperty)*
		public Group getGroup_4_3() { return cGroup_4_3; }

		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }

		//properties+=ModelProperty
		public Assignment getPropertiesAssignment_4_3_1() { return cPropertiesAssignment_4_3_1; }

		//ModelProperty
		public RuleCall getPropertiesModelPropertyParserRuleCall_4_3_1_0() { return cPropertiesModelPropertyParserRuleCall_4_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }

		//("ownedElements" "{" ownedElements+=Model ("," ownedElements+=Model)* "}")?
		public Group getGroup_5() { return cGroup_5; }

		//"ownedElements"
		public Keyword getOwnedElementsKeyword_5_0() { return cOwnedElementsKeyword_5_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5_1() { return cLeftCurlyBracketKeyword_5_1; }

		//ownedElements+=Model
		public Assignment getOwnedElementsAssignment_5_2() { return cOwnedElementsAssignment_5_2; }

		//Model
		public RuleCall getOwnedElementsModelParserRuleCall_5_2_0() { return cOwnedElementsModelParserRuleCall_5_2_0; }

		//("," ownedElements+=Model)*
		public Group getGroup_5_3() { return cGroup_5_3; }

		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }

		//ownedElements+=Model
		public Assignment getOwnedElementsAssignment_5_3_1() { return cOwnedElementsAssignment_5_3_1; }

		//Model
		public RuleCall getOwnedElementsModelParserRuleCall_5_3_1_0() { return cOwnedElementsModelParserRuleCall_5_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class ActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Action");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cActionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cActionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cNextPageKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cNextPageAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cNextPageViewCrossReference_4_1_0 = (CrossReference)cNextPageAssignment_4_1.eContents().get(0);
		private final RuleCall cNextPageViewEStringParserRuleCall_4_1_0_1 = (RuleCall)cNextPageViewCrossReference_4_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Action:
		//	{Action} "Action" name=EString "{" ("nextPage" nextPage=[View|EString])? "}";
		public ParserRule getRule() { return rule; }

		//{Action} "Action" name=EString "{" ("nextPage" nextPage=[View|EString])? "}"
		public Group getGroup() { return cGroup; }

		//{Action}
		public Action getActionAction_0() { return cActionAction_0; }

		//"Action"
		public Keyword getActionKeyword_1() { return cActionKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("nextPage" nextPage=[View|EString])?
		public Group getGroup_4() { return cGroup_4; }

		//"nextPage"
		public Keyword getNextPageKeyword_4_0() { return cNextPageKeyword_4_0; }

		//nextPage=[View|EString]
		public Assignment getNextPageAssignment_4_1() { return cNextPageAssignment_4_1; }

		//[View|EString]
		public CrossReference getNextPageViewCrossReference_4_1_0() { return cNextPageViewCrossReference_4_1_0; }

		//EString
		public RuleCall getNextPageViewEStringParserRuleCall_4_1_0_1() { return cNextPageViewEStringParserRuleCall_4_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class ModelPropertyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ModelProperty");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cModelPropertyAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cModelPropertyKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		
		//ModelProperty:
		//	{ModelProperty} "ModelProperty" name=EString;
		public ParserRule getRule() { return rule; }

		//{ModelProperty} "ModelProperty" name=EString
		public Group getGroup() { return cGroup; }

		//{ModelProperty}
		public Action getModelPropertyAction_0() { return cModelPropertyAction_0; }

		//"ModelProperty"
		public Keyword getModelPropertyKeyword_1() { return cModelPropertyKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
	}
	
	
	private UIApplicationElements pUIApplication;
	private ViewElements pView;
	private ModelElements pModel;
	private EStringElements pEString;
	private ActionElements pAction;
	private ModelPropertyElements pModelProperty;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyApplicationGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.banque.application.MyApplication".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//UIApplication:
	//	{UIApplication} "UIApplication" "{" ("pages" "{" pages+=View ("," pages+=View)* "}")? ("models" "{" models+=Model (","
	//	models+=Model)* "}")? "}";
	public UIApplicationElements getUIApplicationAccess() {
		return (pUIApplication != null) ? pUIApplication : (pUIApplication = new UIApplicationElements());
	}
	
	public ParserRule getUIApplicationRule() {
		return getUIApplicationAccess().getRule();
	}

	//View:
	//	"View" name=EString "{" ("description" description=EString)? "model" model=[Model|EString] ("actions" "{"
	//	actions+=Action ("," actions+=Action)* "}")? "}";
	public ViewElements getViewAccess() {
		return (pView != null) ? pView : (pView = new ViewElements());
	}
	
	public ParserRule getViewRule() {
		return getViewAccess().getRule();
	}

	//Model:
	//	{Model} "Model" name=EString "{" ("properties" "{" properties+=ModelProperty ("," properties+=ModelProperty)* "}")?
	//	("ownedElements" "{" ownedElements+=Model ("," ownedElements+=Model)* "}")? "}";
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return (pEString != null) ? pEString : (pEString = new EStringElements());
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//Action:
	//	{Action} "Action" name=EString "{" ("nextPage" nextPage=[View|EString])? "}";
	public ActionElements getActionAccess() {
		return (pAction != null) ? pAction : (pAction = new ActionElements());
	}
	
	public ParserRule getActionRule() {
		return getActionAccess().getRule();
	}

	//ModelProperty:
	//	{ModelProperty} "ModelProperty" name=EString;
	public ModelPropertyElements getModelPropertyAccess() {
		return (pModelProperty != null) ? pModelProperty : (pModelProperty = new ModelPropertyElements());
	}
	
	public ParserRule getModelPropertyRule() {
		return getModelPropertyAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
