/*
* generated by Xtext
*/
package org.xtext.banque.application;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MyApplicationStandaloneSetup extends MyApplicationStandaloneSetupGenerated{

	public static void doSetup() {
		new MyApplicationStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

