/*
 * generated by Xtext
 */
package org.xtext.banque.application;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyApplicationRuntimeModule extends org.xtext.banque.application.AbstractMyApplicationRuntimeModule {

}
