/*
* generated by Xtext
*/
package org.xtext.banque.application.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.banque.application.services.MyApplicationGrammarAccess;

public class MyApplicationParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MyApplicationGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.banque.application.parser.antlr.internal.InternalMyApplicationParser createParser(XtextTokenStream stream) {
		return new org.xtext.banque.application.parser.antlr.internal.InternalMyApplicationParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "UIApplication";
	}
	
	public MyApplicationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MyApplicationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
