/**
 * generated by Xtext
 */
package org.xtext.banque.application.validation;

import org.xtext.banque.application.validation.AbstractMyApplicationValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class MyApplicationValidator extends AbstractMyApplicationValidator {
}
