/*
 * generated by Xtext
 */
package org.xtext.banque.application.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MyApplicationUiModule extends org.xtext.banque.application.ui.AbstractMyApplicationUiModule {
	public MyApplicationUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
